---
apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: web-service
  labels:
    tier: frontend
spec:
#  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
 #   nodePort: 31004
  selector:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE
  name: DEPLOYMENT
  labels:
    tier: frontend
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
# ImagePullSecret is for pulling from out of this AWS Account.
#      imagePullSecrets:
 #     - name: ecr-cred
      containers:
      - name: DEPLOYMENT
        image: 401413892014.dkr.ecr.REGION.amazonaws.com/REPOSITORY:VERSION
        ports:
        - name: web
          containerPort: 80
        - name: nodejs
          containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_HOST
          value: "http://api-service.NAMESPACE.svc.cluster.local:3000"
---
