---
apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: api-service
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE
  name: DEPLOYMENT
  labels:
    tier: backend
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
#      imagePullSecrets:
 #     - name: ecr-cred
      containers:
      - name: DEPLOYMENT
        image: 401413892014.dkr.ecr.REGION.amazonaws.com/REPOSITORY:VERSION
        ports:
        - name: nodejs-port
          containerPort: 3000
        - name: web
          containerPort: 80
        env:
        - name: PORT
          value: "3000"
        - name: DB
          valueFrom:
            secretKeyRef:
              name: KUBESECRET
              key: host
---
